packages: []

catalog:
  '@iconify/json': ^2.2.326
  '@iconify/vue': ^4.3.0
  '@vicons/carbon': ^0.13.0
  colord: ^2.9.3
  naive-ui: ^2.41.0
  sass-embedded: ^1.86.3
  vue-draggable-plus: ^0.6.0
catalogs:

  build:
    '@iconify-json/carbon': ^1.2.8
    '@vitejs/plugin-vue': ^5.2.3
    unocss: ^66.1.0-beta.7
    unplugin: ^2.2.2
    unplugin-auto-import: ^19.1.2
    unplugin-vue-components: ^28.4.1
    vite: ^6.2.3
  dev:
    '@antfu/eslint-config': ^4.11.0
    '@types/node': ^22.13.14
    '@unocss/eslint-plugin': ^66.1.0-beta.7
    eslint: ^9.23.0
    eslint-plugin-format: ^1.0.1
    lint-staged: ^15.5.0
    pinia: ^3.0.2
    pinia-plugin-persistedstate: ^4.2.0
    simple-git-hooks: ^2.12.1
    typescript: ^5.8.2
    vue-i18n: ^10.0.0
    vue-tsc: ^2.2.8
  frontend:
    '@vueuse/core': ^13.0.0
    vue: ^3.5.13
    vue-router: ^4.5.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
